Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.synced_folder  ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
  end

  config.vm.define "master", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.33.10"

    master.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yaml"
        ansible.limit = 'all'
        ansible.inventory_path = "inventory"
    end
  end

  config.vm.define "slave1" do |slave|
      slave.vm.network "private_network", ip: "192.168.33.11"

      slave.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "slave1.yaml"
          ansible.become = true  
      end
  end

  config.vm.define "slave2" do |slave|
      slave.vm.network "private_network", ip: "192.168.33.12"

      slave.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "slave2.yaml"
          ansible.become = true
      end
  end
end
  