---
- name: conf system
  hosts: all

  tasks:
  - name: Install packages
    apt:
       pkg:
       - apache2
       - php
       - php-fpm
       state: present 
       
  - name: edit conf apache2
    lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 81'
        insertafter: '^Listen 80'
        line: Listen 81     

  - name: add config
    copy:
        src: /vagrant/001-php-default.conf
        dest: /etc/apache2/sites-available/001-php-default.conf     

  - name: restart apache2
    service:
        name: apache2
        state: restarted

  - name: change html
    copy:
        src: /vagrant/index.html
        dest: /var/www/html/index.html

  - name: change php
    copy:
        src: /vagrant/index.php
        dest: /var/www/php/index.php         