Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
   config.vm.synced_folder ".", "/vagrant"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "debian9"
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
      
      apt-get install -y apache2
      systemctl enable apache2
      curl https://raw.githubusercontent.com/Fenikks/devops-files/master/02-tools/files/index.html -o /var/www/html/index.html
      curl https://raw.githubusercontent.com/Fenikks/devops-files/master/02-tools/files/index.php -o /var/www/html/index.php
      iptables -A INPUT -p tcp --dport 81 -j ACCEPT
  SHELL

  config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  
end
